name: Quality Check

on: [push, pull_request]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # Only if you have dependencies listed here

    - name: Run Quality Check
      run: |
        python ./scripts/check_quality.py
      continue-on-error: true  # Continue if there are warnings/errors, so we can log the output

    - name: Upload Quality Check Summary
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: check-quality-summary
        path: ./check_quality_summary.txt

    - name: Add Quality Check Summary to Job
      if: always()
      run: |
        echo "### Quality Check Summary" >> $GITHUB_STEP_SUMMARY
        cat check_quality_summary.txt >> $GITHUB_STEP_SUMMARY
