name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    # always run on pull requests
jobs:
  markdown-check:
    name: Check markdown and CSV formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: './.markdownlint.yml'
          args: . 
      - name: Run Python Ampersands Script
        run: python3 check_ampersands.py
      